### ISSUE TITLE
Question about the reduce content width for readability change

### ISSUE THREAD

**Issue by mikefrobbins** [turtlepod/penny#4]
I recently updated my blog site to version 2.1.0 of the Penny WordPress theme and the website pages were much narrower than with version 1.0.0 so I ended up restoring the theme to the older version. Is there an option to make the new version display web pages with the same width that version 1.0.0 used? Based on the readme on GitHub, I noticed that "Reduce content width for readability." was one of the changes in version 2.0.0, but it would be nice to have an option to maintain the previous width since having a wider than usual width was one of the reasons I chose to use this theme.

**Comment by turtlepod** [comment]
Hi Mike,
I'm very sorry for the inconvenience.

To increase the width:
in Penny v.2 I add new feature "custom css". You can navigate to "Appearance > Customize" and then click to "Custom CSS" section and add this css:

```css
#container{ width: 1350px; }
```

I hope this can solve the issue.

**Comment by mikefrobbins** [comment]
That worked perfectly. Thank You!

**Comment by turtlepod** [comment]
That is awesome!
Again, I'm sorry for the inconvenience.
